import AppProvider from "../app-provider";
import "../globals.css";
import { Inter } from "next/font/google";
import { AuthProvider } from "@/context/AuthContext";
import Header from "@/components/common/header";
import Sidebar from "@/components/common/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <AppProvider>
      <AuthProvider>
        <div className="flex h-[100dvh] overflow-hidden">
          {/* Sidebar */}
          <Sidebar />

          {/* Content area */}
          <div className="relative flex flex-col flex-1 overflow-y-auto overflow-x-hidden">
            {/*  Site header */}
            <Header />

            <main className="grow [&>*:first-child]:scroll-mt-16 container my-6">
              {children}
            </main>
          </div>
        </div>
      </AuthProvider>
    </AppProvider>
  );
}
