"use client";

import AppProvider from "./app-provider";
import "./globals.css";
import { Inter } from "next/font/google";
import { AuthProvider } from "@/context/AuthContext";

import toast, { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <html lang="en">
        <body className={inter.className}>
          <AppProvider>
            <AuthProvider>{children}</AuthProvider>
          </AppProvider>
          <Toaster />
        </body>
      </html>
    </>
  );
}
